export enum BetCheckoutActionTypes {
    SELECT_MATCH = "SELECT_MATCH",
    SELECT_SIDE = "SELECT_SIDE",
    ENTER_BID = "ENTER_BID",
    SUBMIT = "SUBMIT",
    CANCEL = "CANCEL",
    SET_LOADING = "SET_BET_CHECKOUT_LOADING",
    SET_ERROR = "SET_ERROR",
    FINALIZE = "FINALIZE"
}
