export enum ActionType {
    START_BET_SUBMISSION = "START_BET_SUBMISSION",
    SELECT_SIDE = "SELECT_SIDE",
    ENTER_AMOUNT = "ENTER_AMOUNT",
    SUBMIT_BET_SUBMISSION = "SUBMIT_BET_SUBMISSION",
    CANCEL_BET_SUBMISSION = "CANCEL_BET_SUBMISSION",
}
